language: node_js
node_js:
  - 14
env:
  global:
    secure: Qg6tuxpn/LRYzY2BYdBx1AKHUJERQGE+0lT1EQUH8vSwMEi5kmqwqcNjlcgHPc0vRJuLMcEqKnl4UDODkHteEYoKh1UX+OtN0FROKczHaVke0jITrx1jV+hnsXeF7LFoU4tI+pF7dxnnjDCZ+BgFqkptnasn5MlQ7rr8BU8jK0KE/oAWK9ebvwBQidV/8oecj9Y9dwZu4bdwmblimvGCfNeBv5DrqxWeoOQl4a1uZ30hvUhUjK6qzD2Bb+tcvVJ2SxVcRYDy+SksTZ9wx5/gBuGUVmlvpw3wHz/u6Bj4W782+H/BZpL00edArApdxFVyejUiZpIllZW+Cx6mKe0oOSdDlwoK+6HKbLTPAewXWi/cW7KbMUSfKSGSsEOGeNjCklMLnNqHz+H+LN93HAyXRIOPjOvaijLOuUKYc3pgtHkawC3MKOjb03+zdaBA/G+2eyCOTeWE59lVbPAX7G4+dTpZrKL4KXCS6DXSKXl/CqNrnUdZmXn82NVBaAe3GkmmuGAcYmX3qfC/S8/g8IMIAVdeX2NSHePorH9APrMmZ8bqy8suQUbWKSiMk1GKR/NpHfmJMe/YUilTzV7dHzHxkNUBpQLI0rB6WPnBO4BfeF0pvc10pGCoQDUqpx9IA0PP5HJCVEp8pjP1yex2RxDn+07VgjwYhad68WBV5XycyxI=
script:
  - npm run build
  - touch dist/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: aDYO7qQaQ9Cv7s2bfq8U1TrKtAZ9s6uC8tEWeyUMDJCSvcO0R4NXcBqOBbezvDReFsMLFwaCWqmU46uIKNX7jpKF+tIfcFIHePzd9DiiHfWEKb/saGU9epd8GiAWbTQCySmyJRJXb5E8zEstyYo9Dc6nOUOyy6Pl3xaRjfmePXCJz/l2rGYRZwzwlXu31Z5lbo5OdF5I8GPmm/X0rBWWhowLamrx3YBP/4jBS8QwlfhnYHB54ccELiF4ufyQNgMJDwvJF5dOllsXzCbrZ6FeLa7AGpSZM3j4NV1+1DfAr7+kjQSuy2PcRR9OwtLYnwHIZdKrX92SfqOXTnzQFiWD8Nn0oUZ9E56sRws9zngBQeuG/8Tjx7EXGOi7T6430AZdLKna6DImc5EQnsgeNcd6+ogqMcDTWWSDVRoW11KXy0eVGQUTyOh9X1fj84vj6E1Ayo60wnaxq/zE+h0Kyg4U2Lv4xTXrxTNoOkOoI3J2lZafnePuTj5B+qdNhjzKVrnSeh++GRfdmhqDYfbcW7OxmRb9nqNyEsmyGzkfwbZDLT3rZ+KS0l3/H4QSFxZynxyY9mrXJKSo5j90dnts10Q60n8QEyVPiH7XZo+VXgKLaruJlZfvWl9J0Tg2GW+0q/ZOtEOvNiOxTuAsg2u2GtNzG98Vym/Jx41D9spJ/h3/EH0=
  keep_history: true
  local_dir: dist/
  on:
    branch: master
