language: node_js
node_js:
- 16
env:
  global:
  - API_BASE_URL=https://stevebunting-mailer.onrender.com
  - API_MAILER_ENDPOINT=/api/mailer/portfolio
  - secure: s2gFnzZp4oUCHM6eImLqs1MtGSLatx8szO0Bd9gK8g3T3Di3M0RMSEhDrweHv6lB0nNQLeN5zTy9ys+PoHv1PMbaDEDnP4utrXepCV6DAATFmxnAqLqrJUong+nMZTcXwQGzE6rF3k/hZHRdtw/fHlJ0WoM7O/+nqLWAh6dhV0oY4tzB8LE8AIdxcF98uHzDzxixGWaZ89OzZDEd9p/KAqGw+Srk/Nfem2XlHyuk0BJTvupzR0ZSCWibTvB0G7IXP7G3rnmfpp8quH50rNWd4pHZJijMaHDA/2IttwZCzVgj7/TgmhV1dHINEcEkbSbtR65RuxuJW329Zfrs00ATzRrnuxdNbVh9YccvPnwQt2lBb5y1W7CEylMnH7KPYG9dg1Q2MrIoyDvUt60org0KGYHCX582lvTev3wJQSVqn4NJEE1u/hXVEvVcaEPANes8CFKufCOS3u9Inhe3f27WxMMvqrWCJaI40NFoynRNX+uLza18xa0ujqadkBiITaq7Qb118KBmQBza/oaaqqjfkOWkzGfgztEkQK3YwiWv7yJFgEAP6xYfX8YWOQsC/V3lpvS8WZW95+s00nAqUqgisvI0Prh4CpD8CGc2x9Ve1Ii8fljRT0Oux0zgFiYZ9dpXhUxz9mK3xV17bZEW9Z2n64C6mYPkwnjMznmwuU5WWME=
script:
- npm run build
- touch dist/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token:
    secure: aDYO7qQaQ9Cv7s2bfq8U1TrKtAZ9s6uC8tEWeyUMDJCSvcO0R4NXcBqOBbezvDReFsMLFwaCWqmU46uIKNX7jpKF+tIfcFIHePzd9DiiHfWEKb/saGU9epd8GiAWbTQCySmyJRJXb5E8zEstyYo9Dc6nOUOyy6Pl3xaRjfmePXCJz/l2rGYRZwzwlXu31Z5lbo5OdF5I8GPmm/X0rBWWhowLamrx3YBP/4jBS8QwlfhnYHB54ccELiF4ufyQNgMJDwvJF5dOllsXzCbrZ6FeLa7AGpSZM3j4NV1+1DfAr7+kjQSuy2PcRR9OwtLYnwHIZdKrX92SfqOXTnzQFiWD8Nn0oUZ9E56sRws9zngBQeuG/8Tjx7EXGOi7T6430AZdLKna6DImc5EQnsgeNcd6+ogqMcDTWWSDVRoW11KXy0eVGQUTyOh9X1fj84vj6E1Ayo60wnaxq/zE+h0Kyg4U2Lv4xTXrxTNoOkOoI3J2lZafnePuTj5B+qdNhjzKVrnSeh++GRfdmhqDYfbcW7OxmRb9nqNyEsmyGzkfwbZDLT3rZ+KS0l3/H4QSFxZynxyY9mrXJKSo5j90dnts10Q60n8QEyVPiH7XZo+VXgKLaruJlZfvWl9J0Tg2GW+0q/ZOtEOvNiOxTuAsg2u2GtNzG98Vym/Jx41D9spJ/h3/EH0=
  keep_history: true
  local_dir: dist/
  on:
    branch: master