name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      API_BASE_URL: https://api.stevebunting.com
      API_MAILER_ENDPOINT: /mailer
      MAILER_SERVICE: PORTFOLIO

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Create .env
        run: printf "API_BASE_URL=$API_BASE_URL\nAPI_MAILER_ENDPOINT=$API_MAILER_ENDPOINT\nMAILER_SERVICE=$MAILER_SERVICE\nRECAPTCHA_API_KEY=${{ secrets.RECAPTCHA_API_KEY }}" > .env

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: |
          npm run eslint:check
          npm run prettier:check

      - name: Build
        run: npm run build

      - name: No Jekyll
        run: touch dist/.nojekyll

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
